name: "bpb_evals"
dump_dir: "./bpb_evals"
metric_log_dir: "./bpb_evals"
ckpt_dir: ""
seed: 42
use_train_data_config: false
apply_doc_boundary_mask: true
context_seqlen: 4096
context_stride: 4096
val_batch_size: 4
val_data_path: data/validation

data:
    root_dir: data/validation
    batch_size: 1
    prefetch_size: 64
    seq_len: 4096
    n_views: 2
    load_async: true
    add_bos: true
    add_eos: true
    tokenizer:
        name: vanilla_hf
        path: infly/OpenCoder-1.5B-Base

distributed:
    # dp_shard: 4
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: true
    sac_config:
        mode: full
        selective_ac_option: 1
    tp_size: 1
